import fs from 'node:fs';
import path from 'node:path';

/**
 * Prefer TypeScript when the scaffold looks like a TS project.
 * @param {string} projectPath
 * @returns {boolean}
 */
export function prefersTypeScript(projectPath) {
  return (
    fs.existsSync(path.join(projectPath, 'tsconfig.json')) ||
    fs.existsSync(path.join(projectPath, 'App.tsx'))
  );
}

/**
 * @param {{ hasMessaging?: boolean, hasNotifee?: boolean }} options
 * @returns {string}
 */
export function buildBootstrapSource(options = {}) {
  const { hasMessaging = false, hasNotifee = false } = options;
  const lines = ['// Generated by create-react-native-setup — safe to edit'];

  if (hasMessaging) {
    lines.push("import messaging from '@react-native-firebase/messaging';");
  }
  if (hasNotifee) {
    lines.push("import notifee, { AndroidImportance } from '@notifee/react-native';");
  }
  lines.push('');

  lines.push('export async function setupNotifications() {');
  if (hasMessaging) {
    lines.push('  await messaging().requestPermission();');
    lines.push('  // Register background handler early (must be outside React components):');
    lines.push('  // messaging().setBackgroundMessageHandler(async remoteMessage => {});');
  }
  if (hasNotifee) {
    lines.push("  await notifee.createChannel({");
    lines.push("    id: 'default',");
    lines.push("    name: 'Default',");
    lines.push('    importance: AndroidImportance.DEFAULT,');
    lines.push('  });');
  }
  if (!hasMessaging && !hasNotifee) {
    lines.push('  // No notification packages were selected.');
  }
  lines.push('}');
  lines.push('');
  lines.push('setupNotifications().catch(console.warn);');
  lines.push('');
  return lines.join('\n');
}

/**
 * Create `src/notifications.js` (or `.ts`) without overwriting an existing file.
 * @param {string} projectPath
 * @param {{ hasMessaging?: boolean, hasNotifee?: boolean, dryRun?: boolean }} options
 * @returns {Promise<{ status: string, detail: string, modulePath?: string }>}
 */
export async function writeNotificationsBootstrap(projectPath, options = {}) {
  const ext = prefersTypeScript(projectPath) ? 'ts' : 'js';
  const srcDir = path.join(projectPath, 'src');
  const filePath = path.join(srcDir, `notifications.${ext}`);
  const modulePath = `./src/notifications`;

  if (options.dryRun) {
    return {
      status: 'skipped',
      detail: `[dry-run] Would write ${path.relative(projectPath, filePath)}`,
      modulePath,
    };
  }

  for (const existing of [
    path.join(srcDir, 'notifications.js'),
    path.join(srcDir, 'notifications.ts'),
  ]) {
    if (fs.existsSync(existing)) {
      return {
        status: 'skipped',
        detail: `Left existing ${path.relative(projectPath, existing)} unchanged`,
        modulePath: `./src/${path.basename(existing, path.extname(existing))}`,
        manualAction: 'Wire notification setup into your existing src/notifications module.',
      };
    }
  }

  fs.mkdirSync(srcDir, { recursive: true });
  fs.writeFileSync(filePath, buildBootstrapSource(options), 'utf8');
  return {
    status: 'applied',
    detail: `Wrote ${path.relative(projectPath, filePath)}`,
    modulePath,
  };
}

/**
 * Ensure the entry file imports the notifications bootstrap once.
 * @param {string} projectPath
 * @param {string} modulePath e.g. `./src/notifications`
 * @param {{ dryRun?: boolean }} [options]
 * @returns {Promise<{ status: string, detail: string }>}
 */
export async function ensureNotificationsImport(projectPath, modulePath, options = {}) {
  const candidates = ['index.js', 'index.tsx', 'index.ts'];
  let filePath;
  for (const name of candidates) {
    const full = path.join(projectPath, name);
    if (fs.existsSync(full)) {
      filePath = full;
      break;
    }
  }
  if (!filePath) {
    return { status: 'failed', detail: 'No index.js/ts/tsx entry file found' };
  }

  if (options.dryRun) {
    return {
      status: 'skipped',
      detail: `[dry-run] Would import '${modulePath}' in ${path.basename(filePath)}`,
    };
  }

  let content = fs.readFileSync(filePath, 'utf8');
  const already =
    content.includes(`'${modulePath}'`) || content.includes(`"${modulePath}"`);
  if (already) {
    return {
      status: 'already-applied',
      detail: `Import of ${modulePath} already present in ${path.basename(filePath)}`,
    };
  }

  content = `import '${modulePath}';\n` + content;
  fs.writeFileSync(filePath, content, 'utf8');
  return {
    status: 'applied',
    detail: `Added import '${modulePath}' to ${path.basename(filePath)}`,
  };
}
